import {
  BrainCircuit,
  BarChart3,
  CheckCircle2,
} from "@/lib/icons";

const explainability = [
  {
    title: "Global Explainability",
    icon: <BarChart3 size={30} />,
    description:
      "Understand overall model behavior through global SHAP feature importance and ranking.",
  },
  {
    title: "Local Explainability",
    icon: <CheckCircle2 size={30} />,
    description:
      "Explain individual predictions using SHAP values for complete prediction transparency.",
  },
  {
    title: "Feature Importance",
    icon: <BrainCircuit size={30} />,
    description:
      "Identify the most influential business features affecting predictions across models.",
  },
];

const benefits = [
  "SHAP Explainability",
  "Feature Importance Ranking",
  "Global & Local Explanations",
  "Transparent Model Decisions",
  "Executive AI Insights",
  "Responsible AI Reporting",
];

export default function ResponsibleAIExplainability() {
  return (

    <section className="space-y-16">

      {/* ====================================================== */}

      <div className="mx-auto max-w-4xl text-center">

        <span
          className="
            rounded-full

            bg-blue-100

            px-5
            py-2

            text-sm
            font-semibold

            uppercase
            tracking-[0.2em]

            text-blue-700

            dark:bg-blue-900/30
            dark:text-blue-300
          "
        >
          Explainability
        </span>

        <h2
          className="
            mt-6

            text-5xl
            font-black

            text-slate-900
            dark:text-white
          "
        >
          Transparent AI Decisions
        </h2>

        <p
          className="
            mx-auto
            mt-6

            max-w-3xl

            text-lg
            leading-8

            text-slate-600
            dark:text-slate-400
          "
        >
          OpenMarTech AI integrates SHAP explainability into the
          complete ML lifecycle, helping stakeholders understand
          model behaviour with confidence.
        </p>

      </div>

      {/* ====================================================== */}

      <div
        className="
          grid
          gap-8

          lg:grid-cols-2
        "
      >

        {/* Left */}

        <div
          className="
            rounded-[32px]

            border
            border-slate-200

            bg-white

            p-10

            shadow-xl

            dark:border-slate-800
            dark:bg-slate-900
          "
        >

          <h3
            className="
              text-3xl
              font-black

              text-slate-900
              dark:text-white
            "
          >
            SHAP Explainability
          </h3>

          <p
            className="
              mt-6

              leading-8

              text-slate-600
              dark:text-slate-400
            "
          >
            Every prediction generated by the OpenMarTech AI platform
            can be interpreted through SHAP explanations. This allows
            business users and data scientists to understand exactly
            why a prediction was made.
          </p>

          <div
            className="
              mt-10

              grid
              gap-5
            "
          >

            {benefits.map((item) => (

              <div
                key={item}
                className="
                  flex
                  items-center
                  gap-4
                "
              >

                <CheckCircle2
                  className="text-emerald-500"
                  size={22}
                />

                <span
                  className="
                    text-lg

                    text-slate-700
                    dark:text-slate-300
                  "
                >
                  {item}
                </span>

              </div>

            ))}

          </div>

        </div>

        {/* Right */}

        <div
          className="
            grid
            gap-6
          "
        >

          {explainability.map((item) => (

            <div
              key={item.title}
              className="
                rounded-[28px]

                border
                border-slate-200

                bg-white

                p-8

                shadow-lg

                transition-all
                duration-300

                hover:-translate-y-2
                hover:border-blue-500
                hover:shadow-2xl

                dark:border-slate-800
                dark:bg-slate-900
              "
            >

              <div className="text-blue-600 dark:text-blue-400">
                {item.icon}
              </div>

              <h3
                className="
                  mt-5

                  text-2xl
                  font-black

                  text-slate-900
                  dark:text-white
                "
              >
                {item.title}
              </h3>

              <p
                className="
                  mt-4

                  leading-8

                  text-slate-600
                  dark:text-slate-400
                "
              >
                {item.description}
              </p>

            </div>

          ))}

        </div>

      </div>

    </section>

  );
}